// src/views/vue/App.vue
<template>
  <div class="l-container">
    <aside class="l-aside">
      <Expander class="c-expander" />
    </aside>

    <main class="l-main">
      <router-view />
    </main>
  </div>
</template>


<script>
  import '@/views/sass/index.sass'
  import Expander from './components/Expander'


  export default {
    name: 'App',
    components: {
      Expander,
    },
    computed: {
      count() {
        return this.$store.getters.getCount
      }
    },
    methods: {
      increment() {
        this.$store.dispatch('incrementCount')
      }
    },
  }
</script>

// src/views/svelte/App.svelte
<script>
  // import 'views/sass/index.sass'
  // import 'views/sass/index.sass'
  import Router from 'svelte-spa-router'
  import Home from 'views/svelte/routes/pages/Home.svelte'
  import Table from 'views/svelte/routes/pages/Table.svelte'
  import Index from 'views/svelte/routes/pages/Index.svelte'
  import Expander from 'views/svelte/routes/components/Expander.svelte'


  const routes = new Map()

  routes.set('/', Home)
  routes.set('/table/', Table)
  routes.set('/index/', Index)
  // routes.set('/index/:storage:/:database:/:version:/:table:/:index:/', Index)

  // // Exact path
  // const routes = {
  //   '/': Home,
  //   '/table/': Table,
  //   '/index/': Index,
  // }
</script>


<div class="l-container">
  <aside class="l-aside">
    <Expander />
  </aside>

  <main class="l-main">
    <Router {routes} />
  </main>
</div>
